title: "Analytical Techniques for Public Administration"
description: "PA 3311 — Texas State University"
author: "Dr. W. Scott Langford"
baseurl: "/pa3311-textbook"
url: "https://scottlangford2.github.io"
theme: just-the-docs
nav_enabled: true
search_enabled: true
